### ISSUE TITLE
Could you please add benchmark?

### ISSUE THREAD

**Issue by PonyPC** [NERanger/yolov5-jetson#1]
We want to have a reference for yolov5 on tensorrt.

**Comment by NERanger** [comment]
Sorry but this project is done in a previous lab I worked in, which means that I do not have any access to the hardware now.

This [repo](https://github.com/wang-xinyu/tensorrtx/tree/master/yolov5) provides a TensorRT implementation of yolov5, you can try it yourself if you have the proper hardware.
