### ISSUE TITLE
怎样使用realsense相机检测？

### ISSUE THREAD

**Issue by Zhang-Yuheng-max** [NERanger/yolov5-jetson#2]
您好，请教一个问题。怎样运行yolov5-realsense.cpp文件，才能使用realsense相机进行检测，需要在终端中输入什么指令启动程序？

**Comment by NERanger** [comment]
先运行下面的命令build整个cmake工程
```cpp
mkdir build // Create new directory for build files
cd build
cmake ..
make
```
编译成功后在build文件夹下应该有一个名字是yolov5-realsense的可执行文件，在realsense相机插入的情况下运行即可

**Comment by NERanger** [comment]
yolov5-realsense.cpp是当时我用来测试功能用的，所以没有在README中提到

**Comment by Zhang-Yuheng-max** [comment]
谢谢您的答复，我在运行的时候出现了如下问题，不知道怎么解决了
tensorrtx/yolov5-jetson/plugin/yololayer.cu:55: nvinfer1::YoloLayerPlugin::YoloLayerPlugin(const void*, size_t): Assertion `d == a + length' failed.
已放弃 (核心已转储)

**Comment by NERanger** [comment]
不好意思这个问题我不太清楚，这个地方的代码并不是我写的。您可以去原repo看一下，我的工作只是用pybind11给原repo的c++代码加上了python的接口

原repo：https://github.com/wang-xinyu/tensorrtx/tree/master/yolov5

**Comment by NERanger** [comment]
关于realsense的使用，Intel官方的仓库里提供了详细的文档：https://github.com/IntelRealSense/librealsense
